global gui_params
import animorph.*;

slider_length = 0.24;
slider_height = 0.01;

left_col_left = 0.03;
left_col_slider_rect = [ left_col_left 0 slider_length slider_height ];

textbox_length = 0.12;
textbox_height = 0.02;
left_col_nametext_rect = [ left_col_left slider_height textbox_length textbox_height ];
left_col_valuetext_rect = [ left_col_left+textbox_length slider_height textbox_length textbox_height ];

top_slider_y = 0.95;
interslider_vertical_gap = 1.6*(slider_height + textbox_height);

intercol_gap = 0.05;

gui_params = struct( ...
   'slider_length', slider_length, ...
   'slider_height', slider_height, ...
   'left_col_left', left_col_left, ...
   'left_col_slider_rect', left_col_slider_rect, ...
   'textbox_length', textbox_length, ...
   'textbox_height', textbox_height, ...
   'left_col_nametext_rect', left_col_nametext_rect, ...
   'left_col_valuetext_rect', left_col_valuetext_rect, ...
   'top_slider_y', top_slider_y, ...
   'interslider_vertical_gap', interslider_vertical_gap, ...
   'intercol_gap', intercol_gap );
