global shape_params

shape_params = struct('value', {}, 'name', {}, 'range', {});
shape_params(1).name = 'size';
shape_params(2).name = 'head length';
shape_params(3).name = 'head ecc1';
shape_params(4).name = 'head ecc2';
shape_params(5).name = 'snout length';
shape_params(6).name = 'snout ecc1';
shape_params(7).name = 'snout ecc2';
shape_params(8).name = 'ear length';
shape_params(9).name = 'ear ecc1'; 
shape_params(10).name = 'ear ecc2';
shape_params(11).name = 'neck length';
shape_params(12).name = 'neck radius';
shape_params(13).name = 'neck taper'; 
shape_params(14).name = 'tail length';
shape_params(15).name = 'tail radius';
shape_params(16).name = 'tail taper'; 
shape_params(17).name = 'eye size'; 
shape_params(18).name = 'eye theta';
shape_params(19).name = 'eye phi'; 
shape_params(20).name = 'thigh length'; 
shape_params(21).name = 'thigh radius';
shape_params(22).name = 'thigh taper'; 
shape_params(23).name = 'leg length'; 
shape_params(24).name = 'leg radius'; 
shape_params(25).name = 'leg taper'; 
shape_params(26).name = 'foot length';
shape_params(27).name = 'foot ecc1'; 
shape_params(28).name = 'foot ecc2'; 
shape_params(29).name = 'up fr leg length';
shape_params(30).name = 'up fr leg radius';
shape_params(31).name = 'up fr leg taper'; 
shape_params(32).name = 'lo fr leg length';
shape_params(33).name = 'lo fr leg radius';
shape_params(34).name = 'lo fr leg taper'; 
shape_params(35).name = 'hand length'; 
shape_params(36).name = 'hand ecc1'; 
shape_params(37).name = 'hand ecc2'; 
shape_params(38).name = 'chest length';
shape_params(39).name = 'chest ecc'; % previously called ecc1 
%shape_params(40).name = 'chest ecc2'; % This does not get used by the drawing code
shape_params(40).name = 'abd length';
%shape_params(42).name = 'abd ecc1'; % This does not get used by the drawing code
shape_params(41).name = 'abd ecc'; % previously called ecc2
shape_params(42).name = 'chest abd ang';
shape_params(43).name = 'neck chest ang';
shape_params(44).name = 'head neck ang';
shape_params(45).name = 'abd thigh ang';
shape_params(46).name = 'thigh leg ang';
shape_params(47).name = 'chest leg ang';
shape_params(48).name = 'front knee ang';
shape_params(49).name = 'ear ang1';
shape_params(50).name = 'ear ang2';
shape_params(51).name = 'tail ang';
shape_params(52).name = 'snout ang';
shape_params(53).name = 'snout inset';
shape_params(54).name = 'leg offset';
shape_params(55).name = 'alpha';

% /* 
%   in the above offsets, everything is relative to size.
%   e.g., lo fr leg length is actually lo fr leg length factor.
%   */

shape_params(1).range = [0.001 10];% 'size'; 
shape_params(2).range = [0.001 1];%head length';
shape_params(3).range = [0.001 1];%head ecc1'; 
shape_params(4).range = [0.001 1];%head ecc2'; 
shape_params(5).range = [0.001 0.5];%snout length';
shape_params(6).range = [0.001 2];%snout ecc1'; 
shape_params(7).range = [0.001 2];%snout ecc2'; 
shape_params(8).range = [0.001 0.03];%ear length'; 
shape_params(9).range = [0.001 30];%ear ecc1'; 
shape_params(10).range = [0.001 30];%ear ecc2';
shape_params(11).range = [0.001 1];%neck length'; 
shape_params(12).range = [0.001 0.2];%neck radius'; 
shape_params(13).range = [0.001 3];%neck taper'; 
shape_params(14).range = [0.001 1];%tail length';
shape_params(15).range = [0.001 0.2];%tail radius';
shape_params(16).range = [0.001 1];%tail taper'; 
shape_params(17).range = [0.001 0.03];%eye size'; 
shape_params(18).range = [-90 90];%eye theta';
shape_params(19).range = [-90 90];%eye phi'; 
shape_params(20).range = [0.001 1];%thigh length';
shape_params(21).range = [0.001 1];%thigh radius';
shape_params(22).range = [0.001 1];%thigh taper'; 
shape_params(23).range = [0.001 1];%leg length'; 
shape_params(24).range = [0.001 0.2];%leg radius'; 
shape_params(25).range = [0.001 1];%leg taper'; 
shape_params(26).range = [0.001 0.2];%foot length'; 
shape_params(27).range = [0.001 5];%foot ecc1'; 
shape_params(28).range = [0.001 5];%foot ecc2'; 
shape_params(29).range = [0.001 1];%up fr leg length'; 
shape_params(30).range = [0.001 0.3];%up fr leg radius';
shape_params(31).range = [0.001 1];%up fr leg taper'; 
shape_params(32).range = [0.001 1];%lo fr leg length';
shape_params(33).range = [0.001 0.2];%lo fr leg radius';
shape_params(34).range = [0.001 2];%lo fr leg taper'; 
shape_params(35).range = [0.001 1];%hand length'; 
shape_params(36).range = [0.001 1];%hand ecc1'; 
shape_params(37).range = [0.001 1];%hand ecc2'; 
shape_params(38).range = [0.001 1];%chest length';
shape_params(39).range = [0.001 1];%chest ecc'; 
%shape_params(40).range = [0.001 1];%chest ecc2'; % not used
shape_params(40).range = [0.001 1];%abd length';
%shape_params(42).range = [0.001 1];%abd ecc1';% not used
shape_params(41).range = [0.001 1];%abd ecc';
shape_params(42).range = [-90 90];%chest abd ang';
shape_params(43).range = [-90 90];%neck chest ang';
shape_params(44).range = [-90 90];%head neck ang';
shape_params(45).range = [0 180];%abd thigh ang';
shape_params(46).range = [-150 150];%thigh leg ang';
shape_params(47).range = [0 180];%chest up fr leg ang';
shape_params(48).range = [-90 90];%front knee ang';
shape_params(49).range = [-90 90];%head ear ang1';
shape_params(50).range = [-90 90];%head ear ang2';
shape_params(51).range = [-90 90];%abd tail ang';
shape_params(52).range = [-90 90];%snout ang';
shape_params(53).range = [0.001 2];%snout inset';
shape_params(54).range = [0.001 2];%leg offset';